apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployapp
  namespace: demoapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-docker-service
  minReplicas: 4
  maxReplicas: 20
  # metrics:
  # - type: Resource
  #   resource:
  #     name: cpu
  #     target:
  #       type: Utilization
  #       averageUtilization: 50
